export * from './campaign-add-page/campaign-add-page.module';
export * from './campaign-edit-page/campaign-edit-page.module';
export * from './campaign-list-page/campaign-list-page.module';
export * from './campaign-see-page/campaign-see-page.module';
export * from './campaign-see-page/resultados/resultados.module';
export * from './campaign-see-page/resultados-finales/resultados-finales.module';
export * from './campaign-see-page/results-ccaa-edit/results-ccaa-edit.module';
export * from '@base/pages/campaign/campaign-see-page/ipr/ipr-add-page/ipr.module';
export * from './campaign-see-page/ipr/ipr-edit-page/ipr-edit-page.module';
