export const PHASE_DATOS_INICIALES = 'DATOS_INICIALES';
export const PHASE_DOC_INSPECCION = 'DOC_PLAN_DEFINITIVO';
export const PHASE_BORRADOR_RESULTADOS = 'BORRADOR_DEFINITIVO';
export const PHASE_IMPRESO_DEFINITIVO = 'IMPRESO_DEFINITIVO';
export const PHASE_RESULTADOS_DEFINITIVOS = 'RESULTADOS_DEFINITIVOS';
export const PHASE_RESULTADOS_FINALES = 'FINAL';
export const PHASE_RESULTADOS_FINALES_DEBATE = 'FINAL_DEBATE';
export const PHASE_FICHA_TRANSPARENCIA = 'N_FICHA_TRANSPARENCIA';