INSERT INTO users(ID, NAME, FIRST_SURNAME, SECOND_SURNAME,ID_STATE, CREATED_AT, UPDATED_AT, CREATED_BY, UPDATED_BY)
VALUES(1,'jhon','rojas','silva',1,LOCALTIMESTAMP,'2023-06-10 10:00:00',1,1);

ALTER SEQUENCE seq_users RESTART WITH 5;

